### ISSUE TITLE
Impersonate destroy does not work for every user

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-impersonator#6] opened 2018-01-01 12:30 UTC
# Issue
I have a set of user who can be impersonated and a set of user who can impersonate. When a user impersonate another and then press end impersonate, a 403 permission dined is given.
This is due to the auth check in the ImpersonateeController. When you comment this line everything works fine. Further I would recommend a small error handling.:

```
   public function destroy() : RedirectResponse
    {
        /** This need to be comment **/
		//$this->authorize('impersonation', auth()->user());

        $impersonator = session('impersonator');
		if(!empty($impersonator)){
			$originalSession = session('impersonator-session-data');
			session()->flush();
			session($originalSession);
			auth()->login($impersonator);
			$msg = 'Impersonation Session end successfully.';			 // Message is optional and have to be implemented in layout first
			return back()->with('success',$msg); //using back instead of / 
		}
		else{
			$msg =  'No impersonation session located.';
			return back()->with('error',$msg);  //using back instead of / 
		}       
    }
```

## Environment
Laravel Version: 5.5
Laravel Impersonator Package Version: 0.2.0
PHP Version: 7

**Comment by mikebronner** [comment] 2018-01-01 20:47
Ah! Are you trying to impersonate another user, while already impersonating a user? I would not recommend doing that. I have updated the README with pertinent examples that show how to add items to the menu. The Impersonation link should only be available for users that aren't already being impersonated. I will add a check to the view as well.

**Update:** I see I already have that taken care of in the view. Can you provide a user where this works, and a user where it doesn't work? (`dd($user->toArray())` for me).

I have been unable to replicate this issue.

**Comment by Nowi5** [comment] 2018-01-01 22:33
Hi,  no I don't try to impersonate in a loop ;-) 
The situation is the following:
Admin who is allowed to impersonate, impersonate a user who can be impersonated let name him Tester.
Tester is a simple user and he can't impersonate others. After Admin is ready with impersonating Tester he would like to end the session. But due to the fact that Tester does not have the authorization for using the impersonate class, this fails. So the admin get stuck and need to logout complete and start from scratch. 

```
// User Model
/** https://github.com/GeneaLabs/laravel-impersonator **/
    protected $canImpersonateFlag = false;
    protected $canBeImpersonatedFlag = false;

    public function getCanImpersonateAttribute()
    {
        if ($this->can('canImpersonate')) {
            $this->canImpersonateFlag = true;
        }

        return $this->canImpersonateFlag;
    }

    public function getCanBeImpersonatedAttribute()
    {
        if ($this->can('canBeImpersonated') && $this->cannot('canNotBeImpersonated')) {
            $this->canBeImpersonatedFlag = true;
        }

        return $this->canBeImpersonatedFlag;
    }
```

Roles of my test setting:
Admin: canImpersonate, canNotBeImpersonated
User (Tester): canBeImpersonated

**Comment by mikebronner** [comment] 2018-01-01 22:45
Can you post a sample repo that shows this problem in a functioning environment that I can replicate? I would recommend changing your class to this:

```php
// User Model
/** https://github.com/GeneaLabs/laravel-impersonator **/
    public function getCanImpersonateAttribute()
    {
        return $this->can('canImpersonate') ?? false;
    }

    public function getCanBeImpersonatedAttribute()
    {
        return $this->can('canBeImpersonated') ?? false;
    }
```

I'm wondering if not the logic you have there is causing a problem?

**Comment by mikebronner** [comment] 2018-01-01 23:02
Also, could you provide the stack trace when the failure occurs on line 47 of the controller? (The line with `$this->authorize()`.) Thanks!

**Comment by mikebronner** [comment] 2018-01-03 19:53
Hi @Nowi5 just wanted to follow up: have the recent updates to this package worked for you? Please let me know how you are getting along, I want to make sure things are working as expected for you.

Thanks :)

**Comment by mikebronner** [comment] 2018-10-06 00:00
Closing for now, please reopen if the problem is still occurring.

**Closed as completed by mikebronner** 2018-10-06 00:00 UTC
Labels: unconfirmed bug
